-- Agregar políticas RLS específicas para el campo observaciones
-- Solo el líder y colíder de la mesa pueden editar observaciones

-- Crear una política más específica que permita a líderes y colíderes actualizar el campo observaciones
-- Esto complementa la política existente "Servidores pueden actualizar tracking de su mesa"
-- pero es más específica para el campo de observaciones

-- Nota: Si la política existente no funciona, ejecutar esta política adicional:
-- CREATE POLICY "Servidores pueden actualizar observaciones de su mesa"
-- ON caminantes
-- FOR UPDATE
-- TO authenticated
-- USING (
--   EXISTS (
--     SELECT 1 FROM servidores
--     WHERE servidores.auth_user_id = auth.uid()
--     AND servidores.mesa_id = caminantes.mesa_id
--     AND servidores.mesa_id IS NOT NULL
--     AND (servidores.tipo_servidor = 'lider' OR servidores.tipo_servidor = 'colider')
--   )
-- )
-- WITH CHECK (
--   EXISTS (
--     SELECT 1 FROM servidores
--     WHERE servidores.auth_user_id = auth.uid()
--     AND servidores.mesa_id = caminantes.mesa_id
--     AND servidores.mesa_id IS NOT NULL
--     AND (servidores.tipo_servidor = 'lider' OR servidores.tipo_servidor = 'colider')
--   )
-- );

